# Generated by Django 5.0.6 on 2024-07-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
