# Generated by Django 5.0.6 on 2024-05-19 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='scheduleAppointment',
            new_name='Appointment',
        ),
    ]
