# Generated by Django 5.0.6 on 2024-05-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
