# Generated by Django 5.0.6 on 2024-06-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_meeting_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=800)),
                ('refresh_token', models.CharField(max_length=600)),
                ('expiration', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
