# Generated by Django 5.0.6 on 2024-06-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_googletoken_delete_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googletoken',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
