# Generated by Django 5.0.6 on 2024-06-06 02:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_scheduledmeeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledmeeting',
            name='day',
        ),
        migrations.RemoveField(
            model_name='scheduledmeeting',
            name='month',
        ),
        migrations.RemoveField(
            model_name='scheduledmeeting',
            name='time',
        ),
        migrations.RemoveField(
            model_name='scheduledmeeting',
            name='year',
        ),
        migrations.AddField(
            model_name='scheduledmeeting',
            name='datetime_scheduled',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
